
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
  <meta name="description" content="BCV project homepage" />
  <meta name="keywords" content="DNA, sequencing, basecaller, chromatogram, mixture, deconvolution, Sanger, HMM" />
  <meta name="owner" content="favorov@sensi.org" />
  		<link rel="stylesheet" type="text/css" href="<g:createLinkTo dir='css' file='snazzy.css' /> " />
  <title>Base Caller with Vocabulary (BCV)</title>
</head>
<body>
<tmpl:menu />

<h2>Downloads and installation</h2>
<ul>
<li>
<a href="http://sourceforge.net/projects/basecv/files/0.2/bcv-basecaller/bcv-basecaller-0.2.2.tar.gz/download">bcv-basecaller</a>
<p>Source package for the core BCV executables: </p>
<ul>
<li><em>bcvtrain</em> - trains HMM parameters using a set of chromatograms with known sequence,</li>
<li><em>bcvprep</em> - processes trained HMM parameters, preparing them for use with basecaller,</li>
<li><em>bcvproc</em> - performs chromatogram analysis, deconvolving mixed DNA samples.</li>
</ul>
<p>To build them, you will need <a href="http://www.boost.org/">Boost Libraries</a> Version 1.44 or later. See the README file in the archive for installation instructions.</p>
</li>
</ul>
<p><em>bcvproc</em> relies on the following two packages for preliminary processing of chromatogram files:</p>
<ul>
<li>
<a href="http://sourceforge.net/projects/tracetuner/">TraceTuner</a>
<p><em>ttuner</em> executable from this package processes chromatogram trace files in ABI format, calls pure and mixed bases, evaluates quality values and outputs the results in <em>.phd</em>, <em>.scf</em> and <em>.poly</em> files.</p>
</li>
<li><a href="http://sourceforge.net/projects/basecv/files/0.2/prerequisites/polyscan-3.0.tar.gz/download">PolyScan</a>
<p>This tool is used to further process files generated by TraceTuner. It produces two files, containig physical properties (<em>.fpoly</em>) and p-values (<em>.bqs</em>) for each peak in a chromatogram. The package has been modified to output additional information required by <em>bcvproc</em> (the original version is available <a href="http://genome.wustl.edu/pub/software/polyscan/">here</a>).</p>
</li>
</ul>
<p>For indel detection, the <em>bcv_indel.pl</em> script must be called after running <em>bcvproc</em> to obtain the final results. This script is part of <em>bcvrun</em> package:</p>
<ul>
<li>
<a href="http://sourceforge.net/projects/basecv/files/0.2/bcvrun/bcvrun-0.2.3.tar.gz/download">bcvrun</a>
<p>The package also includes <em>bcv_run.pl</em> script that provides a higher level interface to the BCV pipeline, automatically calling TraceTuner, PolyScan and <em>bcvproc</em> applications.</p>
</li>
</ul>
<p>You will also need to install these two packages:</p>
<ul>
<li>
<a href="http://sourceforge.net/projects/basecv/files/0.2/prerequisites/ABI-1.0.tar.gz/download">ABI</a>
<p><em>bcvrun</em> package depends on this Perl module to parse chromatogram file generated by Applied Biosystems (ABI)
automated DNA sequencer. The <a href="http://search.cpan.org/~malay/ABI/">original version</a> has a bug that has been fixed in this distribution.</p>
</li>
<li>
<a href="http://www.drive5.com/muscle/">MUSCLE</a>
<p>A multiple sequence alignment tool used by both <em>bcvproc</em> executable and <em>bcvrun</em> scripts.</p>
</li>
</ul>
<h3>Setting environment variables</h3>
<p>Several environment variables must be set so that BCV modules will be able to run external applications:
<pre>
    export TTUNERCMD=<em>/shell/command/to/run/ttuner</em>
    export POLYSCANCMD=<em>/shell/command/to/run/polyscan</em>
    export BCVCMD=<em>/shell/command/to/run/bcvproc</em>
    export MSACMD=<em>/shell/command/to/run/muscle</em>
</pre>
Under Cygwin an additional setting may be required:
<pre>
    export LC_ALL="C"
</pre>
</p>
</body>
</html>

